config/routes.rb
PccWeb::Application.routes.draw do
  resource  :search, :controller => :search do
    get :result
  end
  get '/procurements/complex_search' => 'procurements#complex_search'
  resources :procurements

  resources :tenderers
  resources :procuring_entities

  get '/company' => 'company#search'
  get '/company/search' => 'company#search'
  get '/company/complex_search' => 'company#complex_search'

  root :to => 'search#show'
end

app/models/procurement.rb
class Procurement < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :tender_infos
  has_many :tenderers, :through => :tender_infos
  belongs_to :procuring_entity
  def entity_name
    procuring_entity.name
  end
end

app/models/procuring_entity.rb
class ProcuringEntity < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :procurements
end

app/models/search_form.rb
class SearchForm
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  attr_accessor :name, :year, :type

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end
end

app/models/setting.rb
# -*- encoding : utf-8 -*-
class Setting < Settingslogic
  source "#{Rails.root}/config/config.yml"
  namespace Rails.env
end

app/models/tender_info.rb
class TenderInfo < ActiveRecord::Base
  # attr_accessible :title, :body
  scope :winning, where(:winning => true)
  belongs_to :procurement
  belongs_to :tenderer
end

app/models/tenderer.rb
class Tenderer < ActiveRecord::Base
  # attr_accessible :title, :body
  has_many :tender_infos
  has_many :procurements, :through => :tender_infos

  def update_counters!
    self.tender_infos_count = self.tender_infos.count
    self.winning_tender_infos_count = self.tender_infos.winning.count
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :allow_cross_domain_access
  def allow_cross_domain_access
    response.headers["Access-Control-Allow-Origin"] = "*"
    response.headers["Access-Control-Allow-Methods"] = "*"
  end
end

app/controllers/company_controller.rb
#encoding: utf-8
class CompanyController < ApplicationController
  def complex_search
    uri     = URI("http://localhost:9200/g0v/company/_search")
    http    = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.request_uri)
    @query_string =  params[:query_string] || "{}"
    request.body = @query_string
    
    respone = http.request(request)
    @json = respone.body
    respond_to do |format|
      format.html { render :search }
      format.json { send_data @json, :type => "text/json", :disposition => 'inline' }
    end
  end

  def search
    uri     = URI("http://localhost:9200/g0v/company/_search")
    http    = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.request_uri)
    params[:q] ||= "台灣積體電路"
    request.body = <<_EOL_
{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "fields": [
              "_id",
              "公司名稱",
              "姓名"
            ],
            "query": #{params[:q].to_json},
            "default_operator": "and"
          }
        }
      ]
    }
  }
}
_EOL_
    respone = http.request(request)
    @query_string = request.body
    @json = respone.body
    respond_to do |format|
      format.html 
      format.json { send_data @json, :type => "text/json", :disposition => 'inline' }
    end
  end
end

app/controllers/procurements_controller.rb
#encoding: utf-8
class ProcurementsController < ApplicationController
  def index
    @procurements = Procurement.includes(:procuring_entity).order(:finish_at).paginate(:page => params[:page])
  end

  def show
    @procurement = Procurement.includes(:procuring_entity).find(params[:id])
    uri     = URI("http://localhost:9200/g0v/procurement/_search")
    http    = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.request_uri)
    @query_string = '{
    "query": {
      "bool": {
      "must": [
        {"query_string": {"default_field": "標案案號", "query": "'+ @procurement.job_number+ '" } }
      ]
    }
    },
    "size": 10
    }'
    request.body = @query_string
    
    respone = http.request(request)
    @json = JSON.load(respone.body)["hits"]["hits"].first["_source"] if JSON.load(respone.body)["hits"]["hits"].first
    respond_to do |format|
      format.html 
      format.json { send_data @json, :type => "text/json", :disposition => 'inline' }
    end

  end

  def complex_search
    uri     = URI("http://localhost:9200/g0v/procurement/_search")
    http    = Net::HTTP.new(uri.host, uri.port)
    request = Net::HTTP::Post.new(uri.request_uri)
    @query_string =  params[:q] || '{
    "query": {
      "bool": {
      "must": [
        {
            "query_string": {
              "fields": [ "投標廠商.投標廠商.廠商名稱"  ],
              "query": "中華電信"
            }
        }
      ]
    }}}'
    request.body = @query_string
    
    respone = http.request(request)
    @json = respone.body
    respond_to do |format|
      format.html 
      format.json { send_data @json, :type => "text/json", :disposition => 'inline' }
    end
  end

end

app/controllers/procuring_entities_controller.rb
class ProcuringEntitiesController < ApplicationController
  def index
    @q = ProcuringEntity.search(params[:q])
    @procuring_entities = @q.result.order(:entity_code).paginate(:page => params[:page])
  end

  def show
    @procuring_entity = ProcuringEntity.find(params[:id])
    @procurements = @procuring_entity.procurements.order("finish_at")

  end
end

app/controllers/search_controller.rb
# encoding: utf-8
class SearchController < ApplicationController
  respond_to :json, :html
  def show
    @search_string = (params[:search_form] && params[:search_form][:name]) || params[:search] || '雲端'
    respond_with do |f|
      f.html
    end
  end

  def result
    search_string = params[:search] 
    @procuring_entities = Procurement.where(["subject like ?", "%#{search_string}%"]).to_a.group_by(&:procuring_entity)
    cache_key= "search-#{search_string}"
    json= Rails.cache.read(cache_key)
    unless json
      json = render_to_string
      Rails.cache.write(cache_key, json)
    end
    render :text => json, content_type => "text/json"
  end

end

app/controllers/tenderers_controller.rb
class TenderersController < ApplicationController
  def index
    @q = Tenderer.search(params[:q])
    @tenderers = @q.result.paginate(:page => params[:page])
  end

  def show
    @tenderer = Tenderer.find(params[:id])
    @winning_tender_infos = @tenderer.tender_infos.includes(:procurement).where(:winning => true)
    @lose_tender_infos = @tenderer.tender_infos.includes(:procurement).where(:winning => false)
    
    respond_to do |format|
      format.html 
      format.json {
        render :json => @tenderer
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/procurements_helper.rb
module ProcurementsHelper
end

app/helpers/procuring_entities_helper.rb
module ProcuringEntitiesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tenderer_helper.rb
module TendererHelper

  def winning_rate(tenderer)
    rate = sprintf( "%.1f", ((tenderer.winning_tender_infos_count) / (tenderer.tender_infos_count).to_f)*100)
    "#{rate}% (#{tenderer.winning_tender_infos_count}/#{tenderer.tender_infos_count})"
  end
end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal hide fade">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_footer.html.erb
<footer class="footer">
  <%= render_list :class => "nav nav-pills pull-right" do |li|
      #li << link_to( "Link1", "#")
      #li << link_to( "Link2", "#")   
      #li << link_to( "Link3", "#")
      #li << link_to( "Link4", "#")
  end %>
  <p class="copyright">Copyright @2012 <%= Setting.app_name %> All rights reserved.</p>

</footer>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_menu.html.erb
<div class="navbar navbar-fixed-top ">
      <div class="navbar-inner top ">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>

          <%= link_to(Setting.app_name, Setting.domain , :class => "brand" )%>

          <%# render :partial => "common/search_form" %>

   
     
          <div class="nav-collapse">
      
              <%= render_list :class => "nav" do |li|
                li << link_to("標案列表", procurements_path)
                li << link_to("發包單位", procuring_entities_path)
                li << link_to("投標廠商", tenderers_path)
                li << link_to("有趣分析", "/analytic/tender_buddy.html")
              end %>
              
              <%= render :partial => "common/user_nav"%>

          </div>
    </div>
  </div>

  <%= yield :submenu %>

</div>

app/views/common/_search_form.html.erb
 <%= form_tag "/search", :class => "navbar-search", :method => :get do %>
   <span class="nav-toolbar-icon nav-toolbar-icon-search"></span>
   <input type="text" name="q" class="search-query " value="<%= @query_string %>" placeholder="<%= @query_string ||   "Search" %>" />
      
<% end %>

app/views/common/_user_nav.html.erb
<ul class="nav pills pull-right">
    <li>
        <div class="social"> <%#  fb_like(Setting.domain) %> </div>
    </li>
</ul>

app/views/company/search.html.erb
<%= form_tag "/company/search", :class => "form-search", :method => "get" do |f| %>
    <%= label_tag :q, "搜尋:" %>
    <%= text_field_tag :q,params[:q],  :class => "input-medium search-query" %>
    <%= submit_tag "Search", :class => "btn"%>
<% end %>

<h2>搜尋內容</h2>
<pre>
<%= JSON.pretty_generate(JSON.parse(@query_string)) %>
</pre>

<h2>結果</h2>
<pre>
<%= JSON.pretty_generate(JSON.parse(@json)) %>
</pre>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title_tag %>
  <%= render_page_description_meta_tag %>
  <%= render_page_keywords_meta_tag %>
  <%= render_page_image_link_tag %>
  <%= csrf_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  
  <%= yield :stylesheets %>

  <meta property="og:title"       content="<%= page_title ||  SeoHelper.configuration.site_name %>"/>
  <meta property="og:description" content="<%= page_description || SeoHelper.configuration.default_page_description %>"/>
  <meta property="og:image:url"   content="<%= page_image ||  SeoHelper.configuration.default_page_image %>"/>

</head>

<%= render_body_tag %>

<%= render :partial => "common/menu" %>

  <div class="container-fluid">

      <%= notice_message %>

      <div class="content">
        <div class="row-fluid">
          <%= yield %>
          <%= yield (:sidebar) %>
        </div> 
    
      </div>

      <%= render :partial => "common/footer" %>    
  </div>



  

  <%= render :partial => "common/bootstrap_modal" %>    
  <%= render :partial => "common/facebook_js" %>
  <%= render :partial => "common/google_analytics" %>
 
  <%= javascript_include_tag "application" %>

  <%= yield :javascripts %>


</body>
</html>

app/views/pages/welcome.html.erb
<div class="span12">
	<h1> Welcome </h1>
</div>

app/views/procurements/complex_search.html.erb
<%= form_tag "/procurements/complex_search", :method => "get" do |f| %>
    <%= label_tag :q, "搜尋:" %>
    <%= text_area_tag :q, JSON.pretty_generate(JSON.parse(@query_string)), :style => "width:400px;height:300px"%>
    <br>
    <%= submit_tag "Search", :class => "btn"%>
<% end %>

<h2>結果</h2>
<pre>
<%= JSON.pretty_generate(JSON.parse(@json)) %>
</pre>

app/views/procurements/index.html.erb
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>單位</th>
            <th>標案名稱</th>
            <th>決標金額</th>
            <th>決標時間</th>
        </tr>
    </thead>
    <tbody>
        <%= content_tag_for(:tr, @procurements) do |procurement|%>
            <td><%= link_to  procurement.entity_name, procuring_entity_path(procurement.procuring_entity)%></td>
            <td><%= link_to procurement.subject, procurement_path(procurement)%></td>
            <td><%= number_to_currency procurement.price%></td>
            <td><%= procurement.finish_at.strftime('%Y/%m/%d')%></td>
        <% end %>
    </tbody>
</table>
<%= will_paginate @procurements %>

app/views/procurements/show.html.erb
<h2><%= @procurement.subject%></h2>
<%= link_to "原始連結", @procurement.url %>

<h3>參考資料</h3>
<pre>
<%= JSON.pretty_generate(@json) %>
</pre>

app/views/procuring_entities/index.html.erb
<%= search_form_for @q, :class => "form-search" do |f| %>
    <%= f.label :name_cont, "搜尋:"%>
    <%= f.text_field :name_cont, :class => "input-medium search-query" %>
    <%= f.submit :class => "btn"%>
<% end %>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>名稱</th>
        </tr>
    </thead>
    <tbody>
        <%= content_tag_for(:tr, @procuring_entities) do |pe|%>
            <td><%= link_to pe.name, procuring_entity_path(pe)%></td>
        <% end %>
    </tbody>
</table>
<%= will_paginate @procuring_entities %>

app/views/procuring_entities/show.html.erb
<h2><%= @procuring_entity.name%></h2>
<h3>標案</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>標案名稱</th>
        </tr>
    </thead>
    <tbody>
        <%= content_tag_for(:tr, @procurements) do |procurement|%>
            <td><%= link_to procurement.subject, procurement_path(procurement)%></td>
        <% end %>
    </tbody>
</table>

app/views/search/show.html.erb
<%= simple_form_for SearchForm.new(:name => @search_string), :url => '', :method => :get do |f|%>
    <%= f.input :name,   :label => '名稱'%>
    <%= f.submit "submit"%>
<% end %>
<div id="d3graph"></div>

<% content_for :javascripts do %>
    <script>
        show_d3($('input[name="search_form[name]"]').val());
    </script>
<% end %>

app/views/tenderers/index.html.erb
<%= search_form_for @q, :class => "form-search" do |f| %>
    <%= f.label :name_cont, "名稱:", :class=>"control-label"%>
    <%= f.text_field :name_cont, :class => "input-medium" %>

    <%= f.label :tender_infos_count, "投標數:", :class=>"control-label"%>
    <%= f.text_field :tender_infos_count_gteq, :class => "input-mini" %> ~
    <%= f.text_field :tender_infos_count_lteq, :class => "input-mini" %>
    <%= f.label :tender_infos_count, "得標數:", :class=>"control-label"%>
    <%= f.text_field :winning_tender_infos_count_gteq, :class => "input-mini" %> ~
    <%= f.text_field :winning_tender_infos_count_lteq, :class => "input-mini" %>
    <%= f.submit :class => "btn"%>
<% end %>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>統編</th>
            <th>廠商名稱</th>
            <th>得標率</th>
        </tr>
    </thead>
    <tbody>
        <%= content_tag_for(:tr, @tenderers) do |tenderer|%>
            <td><%= tenderer.business_number%></td>
            <td><%=link_to tenderer.name, tenderer_path(tenderer)%> </td>
            <td><a href="<%=tenderer_path(tenderer)%>"><%=winning_rate(tenderer)%></a></td>
        <% end %>
    </tbody>
</table>
<%= will_paginate @tenderers %>

app/views/tenderers/show.html.erb
<h2><%= @tenderer.name%></h2>
<h3>得標</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>發標單位</th>
            <th>標案名稱</th>
        </tr>
    </thead>
    <tbody>
        <%= content_tag_for(:tr, @winning_tender_infos) do |t|%>
            <td><%= t.procurement.procuring_entity.name%></td>
            <td><%= link_to t.procurement.subject, procurement_path(t.procurement)%></td>
        <% end %>
    </tbody>
</table>
<h3>未得標</h3>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>發標單位</th>
            <th>標案名稱</th>
        </tr>
    </thead>
    <tbody>
        <%= content_tag_for(:tr, @lose_tender_infos) do |t|%>
            <td><%= t.procurement.procuring_entity.name%></td>
            <td><%= link_to t.procurement.subject, procurement_path(t.procurement)%></td>
        <% end %>
    </tbody>
</table>